title : Lecture Notes on Fundamental of Data Analysis
author: Antonino Furnari
logo: 'logo.png'

# Short description about the book
description: >-
  Lecture Notes on Fundamental of Data Analysis

execute:
  execute_notebooks           : 'off'

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/antoninofurnari/fadlecturenotes
  path_to_book                : "lecturenotes"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
