name: Build PDF Slides
on:
  push:
    branches:
      - master
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Marp
        run: |
          wget https://github.com/marp-team/marp-cli/releases/download/v3.2.1/marp-cli-v3.2.1-linux.tar.gz
          tar xvf marp-cli-v3.2.1-linux.tar.gz
      - name: Build Marp
        shell: bash -l {0}
        run: mkdir -p lecturenotes/_build/marp; for f in lecturenotes/slides/*.md; do ff=${f/.md/.pdf}; marp $f --pdf --allow-local-files -o lecturenotes/_build/marp/$(basename $ff); done
      - uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: lecturenotes/slides/*.pdf
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "_build/marp/*.pdf"
          allowUpdates: true
          replacesArtifacts: true
          removeArtifacts: true
          tag: "latest"