name: Build HTML and Deploy to GH-PAGES
on:
  push:
    branches:
      - master
jobs:
  build-html-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: fadlecturenotes

      - name: Build QuantEcon Mini Example
        shell: bash -l {0}
        run: jb build lecturenotes/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: lecturenotes/_build/html
          CLEAN: true
